package webService;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * sendmsg service = new sendmsg();
 * SendmsgPortType portType = service.getSendmsgHttpPort();
 * portType.uploadFile(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "sendmsg", targetNamespace = "http://DefaultNamespace", wsdlLocation = "http://120.193.39.85/webservice/services/sendmsg?WSDL")
public class Sendmsg_Service extends Service {

	private final static URL SENDMSG_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(webService.Sendmsg_Service.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = webService.Sendmsg_Service.class.getResource(".");
			url = new URL(baseUrl,
					"http://120.193.39.85/webservice/services/sendmsg?WSDL");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://120.193.39.85/webservice/services/sendmsg?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SENDMSG_WSDL_LOCATION = url;
	}

	public Sendmsg_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public Sendmsg_Service() {
		super(SENDMSG_WSDL_LOCATION, new QName("http://DefaultNamespace",
				"sendmsg"));
	}

	/**
	 * 
	 * @return returns SendmsgPortType
	 */
	@WebEndpoint(name = "sendmsgHttpPort")
	public SendmsgPortType getSendmsgHttpPort() {
		return super.getPort(new QName("http://DefaultNamespace",
				"sendmsgHttpPort"), SendmsgPortType.class);
	}

}
