package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import hscrmwebsrvintf.TReturnInfo;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IHsCRMWebSrv", targetNamespace = "http://tempuri.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IHsCRMWebSrv {

	/**
	 * 
	 * @param piFunctionCode
	 * @param psInputPara
	 * @return returns hscrmwebsrvintf.TReturnInfo
	 */
	@WebMethod(operationName = "IWsPosCommOperate")
	@WebResult(partName = "return")
	public TReturnInfo iWsPosCommOperate(
			@WebParam(name = "piFunctionCode", partName = "piFunctionCode") int piFunctionCode,
			@WebParam(name = "psInputPara", partName = "psInputPara") String psInputPara);

}
